language: php
php:
  - '7.0'
  - '7.1'
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  - composer create-project bmarshall511/stable_starter themes/custom/stable-starter dev-master
